# 정렬
- 배열 값을 기준에 따라 순서대로 배치하는 작업임
- 오름차순/내림차순 정렬 가능함
- 원본 유지 여부 확인 필요함


In [1]:
import numpy as np

In [2]:
#np.sort(ndarray)
# - 정렬된 새 배열을 반환
# - 원본 매열은 유지
# - 원본 데이터 유지 여부는 데이터 전처리에 있어서 중요한 부분이다.
arr =  np.random.randint(1,11,10)
print('arr: ',arr)

print('np.sort(arr): ',np.sort(arr))
print('arr: ',arr)

arr:  [5 5 8 7 3 9 1 3 1 8]
np.sort(arr):  [1 1 3 3 5 5 7 8 8 9]
arr:  [5 5 8 7 3 9 1 3 1 8]


In [3]:
# 내림 차순(역순정렬) -> 슬리이싱 방식 이용
np.sort(arr)[::1]

array([1, 1, 3, 3, 5, 5, 7, 8, 8, 9], dtype=int32)

In [7]:
#2차원 배열 형태의 데이터 정렬
# - axis에 따라 정렬 기준이 달라짐
# axis= None -> 전체(1차원으로 변경 후 전체 정렬)
# axis= 0 -> 각 행 안에서 열 방향으로 정렬
# axis= 1 -> 각 열 안에서 행 방향으로 정렬

np.random.seed(1)
arr = np.random.randint(1,15,(3,4))
print('arr: ',arr)

print('np.sort(arr,axis=None): ')
print(np.sort(arr,axis=None))

print('np.sort(arr,axis=0): ')
print(np.sort(arr,axis=0))

print('np.sort(arr,axis=1): ')
print(np.sort(arr,axis=1))

arr:  [[ 6 12 13  9]
 [10 12  6  1]
 [ 1  2 13  8]]
np.sort(arr,axis=None): 
[ 1  1  2  6  6  8  9 10 12 12 13 13]
np.sort(arr,axis=0): 
[[ 1  2  6  1]
 [ 6 12 13  8]
 [10 12 13  9]]
np.sort(arr,axis=1): 
[[ 6  9 12 13]
 [ 1  6 10 12]
 [ 1  2  8 13]]


## np.argsort()
- 배열 요소를 정렬했을 때의 인덱스를 반환함
- 정렬된 값 자체가 아니라 정렬 순서임
- 실제 정렬값은 `arr[indices]`처럼 다시 인덱싱해야 함


In [11]:
# argsort()의 결과값은 정렬 순서를 만드는 인덱스다

arr = np.array([40,10,20,30])
indices = np.argsort(arr)
print(indices)
print(arr[indices])

[1 2 3 0]
[10 20 30 40]


In [13]:
# 역순정렬

arr = np.array([40,10,20,30])
indices = np.argsort(-arr) # arr *-1
print(indices)
print(arr[indices])

[0 3 2 1]
[40 30 20 10]


In [18]:
# 2차원 argsort(axis=0)
arr =np.array([[30,10,20],
               [60,40,50]])
indices = np.argsort(arr,axis=0)
print(indices)
print(arr[indices])

indices = np.argsort(arr,axis=1)
print(indices)


[[0 0 0]
 [1 1 1]]
[[[30 10 20]
  [30 10 20]
  [30 10 20]]

 [[60 40 50]
  [60 40 50]
  [60 40 50]]]
[[1 2 0]
 [1 2 0]]


In [20]:
# 각 배열의 같은 인덱스 요소가 한 학생의 이름, 점수를 나타내고 있음
# 학생의 이름으로 점수 내림차순 순서로 정렬
names = np.array(['홍길동', '신사임당', '이순신', '유관순'])
scores = np.array([90, 30, 50, 70])


indices = np.argsort(-scores) # [0 3 2 1]
sorted_names = names[indices]
print(sorted_names)

#[홍길동 , 유관순, 이순신, 신사임당]

['홍길동' '유관순' '이순신' '신사임당']


In [21]:
# 우선순위에 따른 작업 정렬(작은 수일수록 높은 우선 순위)
priorities = np.array([3, 1, 2, 5, 4])
tasks = np.array(["Task A", "Task B", "Task C", "Task D", "Task E"])

indices = np.argsort(priorities)
sorted_tasks = tasks[indices]
print(sorted_tasks)

# 결과: ["Task B" "Task C" "Task A" "Task E" "Task D"]

['Task B' 'Task C' 'Task A' 'Task E' 'Task D']
