# ndarray 형태변경
- `reshape()`: 원소 개수는 유지하고 배열 모양만 변경함
- `resize()`: 배열 크기 변경함, 원본 수정 가능함
- `ravel()`: 다차원 배열을 1차원으로 펼침
- `expand_dims()`: 지정 axis에 새 차원 추가함
- `squeeze()`: 크기가 1인 차원 제거함
- `transpose()`: 배열 축을 전치함
- `swapaxes()`: 두 축을 서로 교환함
- `rollaxis()`: 지정 축 위치를 이동함
- `moveaxis()`: 축 순서를 변경함
- `broadcast_to()`: 배열을 지정 shape로 broadcast함
- `broadcast_arrays()`: 여러 배열을 broadcast 가능한 형태로 맞춤
- `concatenate()`: 배열 연결함
- `stack()`: 새 축을 만들며 배열을 쌓음
- `hstack()`: 가로 방향으로 배열을 쌓음
- `vstack()`: 세로 방향으로 배열을 쌓음
- `dstack()`: 깊이 방향으로 배열을 쌓음
- `split()`: 배열을 나눔
- `hsplit()`: 가로 방향으로 배열을 나눔
- `vsplit()`: 세로 방향으로 배열을 나눔
- `dsplit()`: 깊이 방향으로 배열을 나눔
- `tile()`: 배열을 반복 배치함
- `repeat()`: 배열 원소를 반복함
- `unique()`: 중복 제거 후 고유값 반환함
- `flip()`: 배열 원소 순서를 뒤집음
- `fliplr()`: 좌우 방향으로 뒤집음
- `flipud()`: 상하 방향으로 뒤집음
- `roll()`: 배열 원소를 순환 이동함
- `rot90()`: 배열을 90도 회전함


In [1]:
import numpy as np
from tornado.escape import squeeze

In [6]:
# reshape() : 지정된 배열에 차원(모양)을 변경
arr = np.arange(12) #0~11
# arr.reshape(3,4)
#arr.reshape(3,-1) # 3행으로 만들라고 지시, 열의개수는 알아서 계산
# -1 : 남은 차원의 수를 NumPy에게 자동 계산하라고 지시
#arr.reshape(5,-1) # 행의 개수는 전체 size의 약수로만 지정해야 함
arr.reshape(-1,4) #열은 4개, 행은 자동 꼐산
# arr.reshape(-1,-1) 당연히 안됨

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
# ravel : 다차원 배열을 1차원 배열로 변환
# [중요] : ravel()의 결과 1차원 배열은 원본과 값을 공유한다(얕은복사)

arr = np.random.randint(1,10,(3,4))
flat= np.ravel(arr)
print(arr)
print(flat)

[[1 6 8 9]
 [1 9 4 1]
 [7 1 2 4]]
[1 6 8 9 1 9 4 1 7 1 2 4]


In [10]:
# ravel() 결과의 값을 수정 ( 값 공유 확인 )
flat[0]= 100
print(arr)
print(flat)


[[100   6   8   9]
 [  1   9   4   1]
 [  7   1   2   4]]
[100   6   8   9   1   9   4   1   7   1   2   4]


In [12]:
# 깊은 복사본이 필요하면 flatten() 사용
flat2= arr.flatten()
flat2[0]=200
print(arr)
print(flat2)

[[100   6   8   9]
 [  1   9   4   1]
 [  7   1   2   4]]
[200   6   8   9   1   9   4   1   7   1   2   4]


In [22]:
# expend_dims(ndarray. axis): 지정한 축에 차원을 추가
arr = np.arange(1,11)
print('arr.shape: ',arr.shape) #(10,)

arr2 = np.expand_dims(arr, axis=0)
print('axis: 0 추가')
print(arr2,arr2.shape)

arr3 = np.expand_dims(arr, axis=1)
print('axis: 1 추가')
print(arr3,arr3.shape)

arr4 = np.expand_dims(arr2, axis=1)
print(arr4,arr4.shape)

arr.shape:  (10,)
axis: 0 추가
[[ 1  2  3  4  5  6  7  8  9 10]] (1, 10)
axis: 1 추가
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]] (10, 1)
[[[ 1  2  3  4  5  6  7  8  9 10]]] (1, 1, 10)


In [24]:
# squeeze(ndarray, axis) : 지정된 차원(축) 제거
# 단 길이가 1인 축만 제거 가능
arr= np.array([[1,2,3]]) # (1,3)

arr2=np.squeeze(arr,axis=0)
print(arr2,arr2.shape)

[1 2 3] (3,)


In [28]:
arr3 = np.array([[1],[2],[3]])
print(arr3,arr3.shape) #3,1
arr4= np.squeeze(arr3,axis=1)
print(arr4,arr4.shape)

[[1]
 [2]
 [3]] (3, 1)
[1 2 3] (3,)


In [29]:
# 3차원 배열
arr = np.array([[[1, 2, 3]]])
print("arr.shape, arr:", arr.shape, arr)

arr2 = np.squeeze(arr, axis=0)
print("arr2.shape, arr2:", arr2.shape, arr2)

arr.shape, arr: (1, 1, 3) [[[1 2 3]]]
arr2.shape, arr2: (1, 3) [[1 2 3]]


In [36]:
# transpose(ndarray): 전치연산
#- 향과 열을 바꾸는 연산
# 정방(정사각형)행렬 전치 연산
# 전치연산은 행렬 곱을 맞추거나, 데이터 축 방향을 바꿀 때 자주 사용.
arr= np.arange(1,10).reshape(3,3)
print(arr)

print('np.transpose(arr) \n', np.transpose(arr))
print('arr.transpose() \n',arr.transpose())
print('arr.T \n',arr.T)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
np.transpose(arr) 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
arr.transpose() 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
arr.T 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [37]:
#직사각형 행렬 전치연산
arr= np.arange(1,7).reshape(2,3)
print(arr)

print('np.transpose(arr) \n', np.transpose(arr))
print('arr.transpose() \n',arr.transpose())
print('arr.T \n',arr.T)

[[1 2 3]
 [4 5 6]]
np.transpose(arr) 
 [[1 4]
 [2 5]
 [3 6]]
arr.transpose() 
 [[1 4]
 [2 5]
 [3 6]]
arr.T 
 [[1 4]
 [2 5]
 [3 6]]


In [47]:
#행렬 곱(내적연산, dot product)에서 전치연산 활용
#- 행렬곱 조건: 왼쪽행렬의 열의 수 == 오른쪽 행렬의 행의 수 

arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(1,7).reshape(2,3)

print('arr1@arr2.T')
print(arr1 @ arr2.T)

print('arr1.T@arr2')
print(arr1.T @ arr2)

arr1@arr2.T
[[14 32]
 [32 77]]
arr1.T@arr2
[[17 22 27]
 [22 29 36]
 [27 36 45]]
