NumPy를 사용하여 다음과 같은 배열을 생성해 보세요.

1. 크기가 4x3인 모든 값이 0인 배열
2. 크기가 3x3인 모든 값이 1인 배열
3. 0에서 20까지 5씩 증가하는 값으로 구성된 배열
4. 0과 1 사이의 4개의 등간격 값을 가진 배열
5. *크기가 2x2인 정규 분포로 구성된 배열*

In [1]:
import numpy as np


In [9]:
arr1= np.zeros((4,3))
arr2=np.ones((3,3))
arr3 = np.arange(0,21,5)
arr4= np.linspace(0,1,4)

print(arr1)
print(arr2)
print(arr3)
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0  5 10 15 20]
[0.         0.33333333 0.66666667 1.        ]


1. 배열 `arr`에서 1번째 열만 추출
2. 배열 `arr`에서 1번째 행, 2번째 열의 값을 출력
3. 배열 `arr`에서 첫 번째 행부터 두 번째 행까지 선택하고, 0번째와 1번째 열만 추출

In [17]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[:,1])
print(arr[1,1])
print(arr[:2,:2])

[20 50 80]
50
[[10 20]
 [40 50]]


아래 배열에서 팬시 인덱싱과 불리언 인덱싱을 사용하여 다음 작업을 수행하세요.

1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
2. 배열의 값 중 50보다 큰 값만 추출

In [20]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[[0,2,4]])
print(arr[arr>50])


[10 30 50]
[60 70]


어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.

1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.

In [25]:
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

print(sales[sales>200])
print(sales[sales[:,2]<=100,0:2])
print(sales[sales[:,1]>=150,:])

[220 300 320 310]
[[120 150]
 [ 50  45]]
[[120 150 100]
 [200 180 220]
 [300 320 310]]


다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [30]:
 # 사과 ,배, 오렌지, 바나나
q1 =np.array([200,340,150,400])
q2 =np.array([220,300,180,420])
print(q1+q2)
print((q1+q2)/2)

[420 640 330 820]
[210. 320. 165. 410.]


다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

In [32]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


다음 두 배열 간의 내적 연산을 수행하세요.

In [33]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1@arr2)

32


아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

In [35]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
print(arr1d+arr2d)

[[11 22 33]
 [14 25 36]]


1. 배열에서 20보다 큰 값을 찾아 출력하세요.
2. 배열의 합계, 최대값, 최소값, 평균을 계산하세요.

In [42]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr>20])
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))

[30 40 50]
50
10
30.0


아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.

In [50]:
arr = np.array([10, 20, 30, 30, 40, 50, 60])
print("평균:",    np.mean(arr))
print("중앙값:",  np.median(arr))
print("분산:",    np.var(arr))
print("표준편차:", np.std(arr))
print("범위:",    np.max(arr) - np.min(arr))

평균: 34.285714285714285
중앙값: 30.0
분산: 253.06122448979593
표준편차: 15.90789817951435
범위: 50


정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
2. 0과 1 사이의 균등분포 난수 1000개 생성

In [52]:
print(np.random.normal(0,1,1000))

print(np.random.uniform(0,1,1000))


[-4.48339337e-01  6.61389009e-01  1.41598375e+00 -6.86675344e-01
  3.84060176e-01  1.69889607e+00 -1.40872382e+00 -5.31379656e-01
 -1.90121255e+00 -1.76582506e+00 -4.42526139e-01  6.14947654e-01
  6.42222876e-01  1.95641497e+00 -2.35104510e-01  5.34124458e-01
 -2.85494793e-01 -9.27548262e-01  4.00537760e-01  4.17496441e-01
  1.51437103e+00 -3.21119461e-04 -3.84980664e-01 -1.33688862e+00
  2.00537860e-01 -3.84696002e-01  4.40092211e-01  5.54245752e-01
  2.99408039e-01  1.55125799e+00 -1.18220402e+00 -1.04191994e+00
  9.80998845e-02 -7.56952400e-01  5.11935249e-01 -3.70034364e-01
  1.35154626e-01 -1.16444189e-01 -1.81595856e-01 -7.44063614e-02
 -5.12162989e-01  4.60401605e-01 -2.01953768e+00  2.11072047e-01
 -4.04497947e-01  2.60605577e-01  1.71247475e+00 -4.06823232e-01
  5.43413572e-01  3.10091104e-01  2.60258797e-01  6.88712735e-01
  1.06417184e+00  1.61008435e+00 -1.18663542e+00 -1.12077006e+00
  3.34617029e-01 -1.40936122e-01  3.02247199e-01  4.85734635e-01
  5.75035604e-01 -8.88482

아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.

In [57]:
scores_math =    [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

arr=np.array([scores_math, scores_english, scores_science])

print('평균: ',arr.mean(axis=0))
print('분산 : ',np.var(arr))
print('표준편차 : ',np.std(arr))

평균:  [87.66666667 88.33333333 79.33333333 87.         93.66666667 89.
 87.33333333 89.66666667 85.         87.66666667]
분산 :  16.115555555555552
표준편차 :  4.014418457953226


다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.

In [64]:
arr = np.array([50, 10, 30, 40, 20])
print('오름차순: ',np.sort(arr))
print('내림차순: ',np.sort(arr)[::-1])

오름차순:  [10 20 30 40 50]
내림차순:  [50 40 30 20 10]


다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.

In [68]:
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
print('행기준 : ',np.sort(arr2d,axis=0))
print('열기준 : ',np.sort(arr2d,axis=1))

행기준 :  [[2 3 1]
 [8 9 5]]
열기준 :  [[3 5 8]
 [1 2 9]]


다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.

In [ ]:
arr = np.array([15, 10, 20])


다음 두 개의 1차원 배열을 np.concatenate()와 np.hstack()을 사용하여 병합하세요.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

다음 두 개의 2차원 배열을 np.concatenate()와 np.vstack()을 사용하여 각각 병합하세요.

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

In [ ]:
# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])